sudo: required

language: go

go_import_path: github.com/frodenas/stackdriver_exporter

services:
  - docker

jobs:
  include:
    - stage: Run tests
      script: make test

    - stage: Build docker image
      env:
        - DOCKER_IMAGE_NAME=frodenas/stackdriver-exporter
        - secure: JdoxGXoO+9Rq2ZqoeeZ0bxM8z30wPId2M93gqQM78r0UfiSNQz/dHWwkiBKHBkuBtYFHGVX1kl1ExWQHoVaYBKVM2bNmLN/wh03YDnbZSmYOieVzghXSYbFE6cheEgs9dp0/6q6n9g1HKk2j8efCIP5/GGmAUIprs/JTn9HlT6WB3ZiupyC7sMMU8B4i1sNk8LPh1Sv2vaiG+hH7dcNSlfdID+QbCOyU9PCu/+yNKEeI+ifxxgAwadi7N6+xt1wfuBHI4i8+Soy2LI7+fCeYAzE2tjadX0rI83j/+bWq1k5g+Ehqg3avEW3iu2xc+G8RM1XPp7SPQwTgQ1U1QKm8PK8GdNwRjrpujAmTvp5wlZTjd3Q8qgz/Th2gQOWY9Q7rpDYkAubPERtM/+2iu8ZbzUcNaJWNP6hNjK6swN/N2TuxOfXzf0R4p9jhfxVl1s30w1HRGHIgGUQ28CQo4YSZCk7Sat5KCnuvl08+3EaNsklHHUH5/ImhIIcOEojtFuTIDHe6WknYg5UUOw2OfN3rGv3huDl6JRvh6mcqHlpf/hziKtmiS00Cofzl+pPTvzG4CbTLGEATw/c+tj5BXIWG02VCwYPgN4Sm7JXFpS82rZNSi52vX9kCv5tbHLWjYJYaRBIHZCcMhsCk/eWht8huUd2S6JsC63hsapP6CgbZzJ4=
        - secure: tenYAnsn3hCqibeRH7tAk0cGBOFZHfNjh+F4XtZIRqTD+O0L7ZUanqHS0kx0v9W8A3rgvGSlO1Ic5dWIMFJusMDRhF4wEZG0YY3OeW1N26VN8kOUoh8ykUHcbodsqh3Lyn8YsvMxdq66RtRXQeboINDRvIzECPzYSkfBh2u1giQSplVjbEVGSs+4XFKto/HRTPL/zZlkm9b4LczpNTGrLh6TYQJERRRQH+ycH+9KoBc1zBT6BpLKhqfXThbCVZEv6kL303NJ3uU6AbZDekLiYjByvbEOlozoMB8AnTJ5eSP6WZDtq3HZ5C/OJDMxn+0LqJ8uds+xWn9AvFspfN6VTRQzO8U687YuAOxiyguvJQPavmQZn0S6SFbi3wKLfhmfcC7roUB3jZzRFw+ZrKq9qXR5AWm58WUDLPCvHkQC2qKz/irTarurfqL9yPRo0qkSKksTkZLh5QMqpSoa1DUNV3flhDcfOQEJCoUlVLvkOK1SlJR+PMYBQkN0VfoQnMOwHGhU2idGS8fI/YnqKiS/y/0p8nXnPtthL1lTsrJl1XUGDDKlPiBgImjYSPwu+TlQcekMVYaX4OOarBqwpbs3WBCWJo5HBZL7BXmvSadh/sKCZ+jSY+wabOvwupm5NnlaIZWlSo8ym/rIJR5qBiRvF31CiKAuYG7/0e/QdthqsPo=
      script:
        - |
          if [ -n "$TRAVIS_TAG" ]; then
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$TRAVIS_TAG
          else
            make docker DOCKER_IMAGE_NAME=$DOCKER_IMAGE_NAME DOCKER_IMAGE_TAG=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
          fi
        - |
          if [[ "$TRAVIS_TAG" =~ ^v[0-9]+(\.[0-9]+){2}$ ]]; then
            docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_TAG" "$DOCKER_IMAGE_NAME:latest"
          fi
        - docker images
        - |
          if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
            docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
            docker push $DOCKER_IMAGE_NAME
          fi
